# Authentification par mot de passe
allow_anonymous false
password_file /etc/mosquitto/passwd

# Listener par défaut
listener 1883 0.0.0.0

# Chiffrement TLS
listener 8883 0.0.0.0
cafile /etc/mosquitto/certs/server.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key

# ACL (contrôle d'accès par topic)
acl_file /etc/mosquitto/acl
